# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Untrusted part of the Freescale Ethernet controller
#

obj-$(CONFIG_FEC_BSTGW) += fec_bstgw.o
fec_bstgw-objs :=bstgw_fec_main.o bstgw_fec_ptp.o

